### PR TITLE
Demote remaining 9x cat A items to cat B

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by johanmalm** [comment]
@Consolatis There are 9 Cat A items left. They were all selected as Cat A a long time ago, and where we are I don't think they are "must haves" for minimum viable product. I vote for downgrading them to Bs. Are you happy with that?

**Comment by Consolatis** [comment]
`window.handle.width` is the "invisible area around a window which allows resizing"?
If yes I'd vote for a `B+` on that one, the others indeed seem good candidates for `B` to me.

**Comment by johanmalm** [comment]
"handle" refers to (from openbox wiki): `The window handle is the piece of decorations on the bottom of windows`

See circled item

20220625_10h04m35s_grim

Today we don't support handles. And I personally think the look a big ugly.
I did think we could use it to specify the size of the SSD corner pieces which allow combined vertical/horizontal resize, but on second thought we wouldn't want themes to implicitly affect that, so if we really care about allowing the user to specify it, I'd vote for adding that to rc.xml as a core configuration option.

**Comment by Consolatis** [comment]
Then I'd also be fine to throw the window handle stuff into cat C but have no strong position regarding B or C.

I think we should provide some option (core or theme) to define the width of "the invisible area around the window which allows resizing" though.

**Pull request merged**
